In [11]:
from scipy.stats import t
from scipy.linalg import pinvh as inv
from numpy.linalg import lstsq
import numpy.matlib as mb
import ipywidgets as widgets
import math as mt
import numpy as np
import pandas as pd
import re   

# Calibração

In [12]:
def MMQ(y, mx):
  coef = (inv(mx.T @ mx)) @ (mx.T @ y) # Faz a linearização com os dados
  return (coef)

In [13]:
def RMSE(yReal, yEstimado): # root-mean-square deviation
  residuos = np.sum(np.power((yReal - yEstimado),2))**0.5
  return(residuos)

In [14]:
def calcular_r2(y_true, y_pred):
    """
    Calcula o coeficiente de determinação R².
    
    Parâmetros:
    y_true: array-like, Valores observados (reais).
    y_pred: array-like, Valores preditos pelo modelo.
    
    Retorno:
    r2: float, Coeficiente de determinação R².
    """
    # Converter para arrays do NumPy, caso não sejam
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    
    # Média dos valores observados
    y_mean = np.mean(y_true)
    
    # Soma dos quadrados dos resíduos (SSR)
    ss_res = np.sum((y_true - y_pred) ** 2)
    
    # Soma total dos quadrados (SST)
    ss_tot = np.sum((y_true - y_mean) ** 2)
    
    # Cálculo de R²
    r2 = 1 - (ss_res / ss_tot)
    
    return r2

## Caso 1: Sistema de 1º Ordem sendo avaliado por diversas ordens

In [15]:
x = np.matrix([410.0,389.0,329.0,307.0,261.0])
y = np.matrix([453.0,500.0,674.0,758.0,988.0])

In [16]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[-3.49666414]] [[1860.66847472]]
[[453. 500. 674. 758. 988.]] 
 [[427.03617921 500.46612606 710.26597418 787.19258516 948.03913539]]
66.62308815614193
0.9759771438033317


In [17]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[0.01296393]] [[-12.2612844]] [[3303.80050555]]
[[453. 500. 674. 758. 988.]] 
 [[455.91118097 495.87630737 673.06710131 761.42399574 986.72141462]]
6.3014794192308825
0.9997850882468805


In [18]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[9.34892517e-05]] [[-0.08041748]] [[18.38318761]] [[0.17078185]]
[[453. 500. 674. 758. 988.]] 
 [[462.47262459 485.51687089 673.04419595 769.60206293 982.26355667]]
21.631455178732757
0.9974675166742283


In [ ]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.exp(x.T/100), np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*np.exp(x)+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

C:\Users\Administrator\AppData\Local\Temp\ipykernel_68876\804333547.py:2: RuntimeWarning: overflow encountered in matmul
  coef = (inv(mx.T @ mx)) @ (mx.T @ y) # Faz a linearização com os dados


ValueError: array must not contain infs or NaNs